package com.uu_uce.fieldbook

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Holds the pin data as it's stored in the database
 * It's stored to a table called "pins"
 *
 * @property[id] is the primary key and is autogenerated, gives an unique index to each FieldbookEntry
 * @property[title] the title of the fieldbook item
 * @property[location] the location (UTM Coordinates)
 * @property[dateTime] the date and time on which this FieldbookEntry has been made
 * @property[content] the content shown in the entry, as a JSON String
 * @constructor builds one PinData object with the given data
 */
@Entity(tableName = "fieldbook")
class FieldbookEntry(
    var title          : String,
    var location       : String,
    var dateTime       : String,
    var content        : String
) {
    @PrimaryKey(autoGenerate = true) var id: Int = 0
}


