name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd ./app; sudo ./gradlew build; cd ..;
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: cd ./app; sudo ./gradlew test --stacktrace; cd ..;
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: cd ./app; sudo ./gradlew assembleDebug --stacktrace; cd ..;
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/app/build/outputs/apk/debug/app-debug.apk
