name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd ./preprocessing; cargo build --verbose
    - name: Run tests
      run: cd ./preprocessing; cargo test --verbose
